### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by f466162** [voodoodyne/subethasmtp#95]
As there is neither a commit from 2019, nor any issue: Is this project still alive? I'm currently looking for a SMTPD solution in plain Java and SubEtha looks promising, but I'm unsure whether SubEtha is still maintained.

Regards
- Fabian

**Comment by davidmoten** [comment]
Hi Fabian, active fork with a number of improvements at https://github.com/davidmoten/subethasmtp.

**Comment by f466162** [comment]
Hi David

thanks a lot for this hint! I'll take a look and I'm really glad someone takes care of this project. 👍
